CREATE TABLE SISTEMA_PLANETARIO(
    NOME VARCHAR2(50),
    GALAXIA VARCHAR2(50),
    DISTANCIA NUMBER(20),
    IDADE_ESTIMADA NUMBER(20),
    TIPO_ESTRELA_CENTRAL VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_SISTEMA_PLANETARIO PRIMARY KEY (NOME, GALAXIA)
);

CREATE TABLE ESTRELA(
 	NOME_SISTEMA VARCHAR2(50),
    GALAXIA VARCHAR2(50),
   	ESTRELA VARCHAR2(50),
    CONSTRAINT PK_ESTRELA PRIMARY KEY (NOME_SISTEMA, GALAXIA, ESTRELA),
    CONSTRAINT FK_ESTRELA FOREIGN KEY (NOME_SISTEMA, GALAXIA) REFERENCES SISTEMA_PLANETARIO(NOME, GALAXIA) ON DELETE CASCADE
);

CREATE TABLE PLANETA(
	ID NUMBER(15),
    SISTEMA_PLANETARIO VARCHAR2(50) NOT NULL,
    GALAXIA VARCHAR2(50) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    TEMPERATURA NUMBER(4),
    PRESSAO NUMBER(4),
    CLIMA VARCHAR2(20),
    CONSTRAINT PK_PLANETA PRIMARY KEY (ID),
    CONSTRAINT FK_PLANETA FOREIGN KEY (SISTEMA_PLANETARIO, GALAXIA) REFERENCES SISTEMA_PLANETARIO(NOME, GALAXIA) ON DELETE CASCADE,  
    CONSTRAINT SK_PLANETA UNIQUE (SISTEMA_PLANETARIO, GALAXIA, NOME)
);

CREATE TABLE SATELITE_NATURAL(
    PLANETA NUMBER(15),
    SATELITE VARCHAR2(50), 
    CONSTRAINT PK_SATELITE_NATURAL PRIMARY KEY (PLANETA, SATELITE),
    CONSTRAINT FK_SATELITE_NATURAL FOREIGN KEY (PLANETA) REFERENCES PLANETA(ID) ON DELETE CASCADE
);

CREATE TABLE COMPOSICAO_ATMOSFERICA(
    PLANETA NUMBER(15),
    ELEMENTO VARCHAR2(50), 
    PORCENTAGEM NUMBER(3) NOT NULL,
    CONSTRAINT PK_COMPOSICAO_ATMOSFERICA PRIMARY KEY (PLANETA, ELEMENTO),
    CONSTRAINT FK_COMPOSICAO_ATMOSFERICA FOREIGN KEY (PLANETA) REFERENCES PLANETA(ID) ON DELETE CASCADE
);

CREATE TABLE CIVILIZACAO(
    NOME VARCHAR2(50),
    CATEGORIA CHAR(1),
    CLASSIFICACAO CHAR(3) NOT NULL,
    PLANETA_ORIGEM NUMBER(15) NOT NULL,
    CONSTRAINT PK_CIVILIZACAO PRIMARY KEY (NOME, CATEGORIA),
    CONSTRAINT FK_CIVILIZACAO FOREIGN KEY (PLANETA_ORIGEM) REFERENCES PLANETA(ID) ON DELETE CASCADE
);

CREATE TABLE CIVILIZACAO_HABITA_PLANETA(
    NOME_CIVILIZACAO VARCHAR2(25),
    CATEGORIA_CIVILIZACAO CHAR(1),
    PLANETA NUMBER(15),
    CONSTRAINT PK_CIVILIZACAO_HABITA_PLANETA PRIMARY KEY (NOME_CIVILIZACAO, CATEGORIA_CIVILIZACAO, PLANETA),
    CONSTRAINT FK_CIVILIZACAO_HABITA_PLANETA FOREIGN KEY (NOME_CIVILIZACAO, CATEGORIA_CIVILIZACAO) REFERENCES CIVILIZACAO(NOME, CATEGORIA) ON DELETE CASCADE
);

CREATE TABLE ROTA(
    ORIGEM NUMBER(15),
    DESTINO NUMBER(15),
    DISTANCIA NUMBER(20) NOT NULL,
   	CONSTRAINT PK_ROTA PRIMARY KEY (ORIGEM, DESTINO),
    CONSTRAINT FK_ROTA1 FOREIGN KEY (ORIGEM) REFERENCES PLANETA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROTA2 FOREIGN KEY (DESTINO) REFERENCES PLANETA(ID) ON DELETE CASCADE,
    CONSTRAINT CK_ROTA CHECK (ORIGEM <> DESTINO)
);


CREATE TABLE AMEACA (
 	NOME VARCHAR2(50),
	DESCRICAO VARCHAR2(100) NOT NULL,
	NIVEL NUMBER(5) NOT NULL,
 	CONSTRAINT PK_AMEACA PRIMARY KEY (NOME)
);

CREATE TABLE BASE_ESPACIAL (
 	PLANETA NUMBER(15),
    NOME VARCHAR2(50),
	TIPO  VARCHAR2(25),
	CAPACIDADE NUMBER(10),
	CANAL_COMUNICACAO VARCHAR2(50),
 	CONSTRAINT PK_BASE_ESPACIAL PRIMARY KEY (NOME, PLANETA),
	CONSTRAINT FK_BASE_ESPACIAL FOREIGN KEY (PLANETA)  REFERENCES PLANETA(ID) ON DELETE CASCADE
);


CREATE TABLE MISSAO_ESPACIAL (
    ID NUMBER(15),
    PLANETA_BASE NUMBER(15) NOT NULL,
    NOME_BASE VARCHAR2(50) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    DESCRICAO VARCHAR2(100) NOT NULL,
    TAMANHO_TRIPULACAO NUMBER(15),
    OBJETIVO VARCHAR2(50) NOT NULL,
    DURACAO_ESTIMADA NUMBER(15),
    NIVEL_PERICULOSIDADE NUMBER(15) NOT NULL,
 	CONSTRAINT PK_MISSAO_ESPACIAL PRIMARY KEY (ID),
  	CONSTRAINT FK_MISSAO_ESPACIAL FOREIGN KEY (PLANETA_BASE, NOME_BASE)  REFERENCES BASE_ESPACIAL(PLANETA, NOME) ON DELETE CASCADE,
	CONSTRAINT SK_MISSAO_ESPACIAL UNIQUE (PLANETA_BASE, NOME_BASE, NOME, DATA_INICIO),
    CONSTRAINT CK_MISSAO_ESPACIAL CHECK (DATA_FIM > DATA_INICIO)
);

CREATE TABLE NAVE (
	ID NUMBER(15),
	NOME VARCHAR2(50) NOT NULL,
	CLASSE VARCHAR2(50) NOT NULL,
	MAX_TRIPULACAO NUMBER(15),
	RESISTENCIA NUMBER(15),
	LOC_ATUAL VARCHAR2(50) NOT NULL,
    PLANETA_BASE NUMBER(15) NOT NULL,
    NOME_BASE VARCHAR2(50) NOT NULL,
 	CONSTRAINT PK_NAVE PRIMARY KEY (ID),
    CONSTRAINT FK_NAVE FOREIGN KEY (PLANETA_BASE, NOME_BASE)  REFERENCES BASE_ESPACIAL(PLANETA, NOME),
	CONSTRAINT SK_NAVE UNIQUE (NOME, CLASSE)
);

CREATE TABLE AMEACA_ROTA(
	ORIGEM_ROTA NUMBER(15),
	DESTINO_ROTA NUMBER(15),
	NOME_AMEACA  VARCHAR2(50),
 	CONSTRAINT PK_AMEACA_ROTA PRIMARY KEY (ORIGEM_ROTA, DESTINO_ROTA, NOME_AMEACA),
	CONSTRAINT FK_AMEACA_ROTA1 FOREIGN KEY (ORIGEM_ROTA, DESTINO_ROTA) REFERENCES ROTA(ORIGEM, DESTINO) ON DELETE CASCADE,
    CONSTRAINT FK_AMEACA_ROTA2 FOREIGN KEY (NOME_AMEACA) REFERENCES AMEACA(NOME) ON DELETE CASCADE
);

CREATE TABLE ROTA_MISSAO(
	MISSAO NUMBER(15),
	ORIGEM_ROTA NUMBER(15),
	DESTINO_ROTA NUMBER(15),
	ORDEM NUMBER(15) NOT NULL,
 	CONSTRAINT PK_ROTA_MISSAO PRIMARY KEY (MISSAO, ORIGEM_ROTA, DESTINO_ROTA),
	CONSTRAINT FK_ROTA_MISSAO1 FOREIGN KEY (MISSAO) REFERENCES MISSAO_ESPACIAL(ID) ON DELETE CASCADE,
	CONSTRAINT FK_ROTA_MISSAO2 FOREIGN KEY (ORIGEM_ROTA, DESTINO_ROTA) REFERENCES ROTA(ORIGEM, DESTINO) ON DELETE CASCADE,
    CONSTRAINT SK_ROTA_MISSAO UNIQUE(MISSAO, ORDEM)
);

CREATE TABLE AMEACA_PLANETA (
	PLANETA NUMBER(15),
	AMEACA VARCHAR2(50),
 	CONSTRAINT PK_AMEACA_PLANETA PRIMARY KEY (PLANETA, AMEACA),
	CONSTRAINT FK_AMEACA_PLANETA1 FOREIGN KEY (PLANETA)  REFERENCES PLANETA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AMEACA_PLANETA2 FOREIGN KEY (AMEACA) REFERENCES AMEACA(NOME) ON DELETE CASCADE
);

CREATE TABLE RECURSO_NATURAL (
	NOME VARCHAR2(50),
	TIPO VARCHAR2(50),
 	CONSTRAINT PK_RECURSO_NATURAL PRIMARY KEY (NOME, TIPO)
);

CREATE TABLE PRODUTO (
	NOME VARCHAR2(50),
	ORIGEM VARCHAR2(50),
	DESCRICAO VARCHAR2(100) NOT NULL,
	PRECO NUMBER(15,2) NOT NULL,
	PESO NUMBER(15,2),
 	CONSTRAINT PK_PRODUTO PRIMARY KEY (NOME, ORIGEM)
);

CREATE TABLE RECURSO_PLANETA(
	PLANETA NUMBER(15),
	NOME_REC VARCHAR2(50),
	tipo_REC VARCHAR2(50),
	ESTIMATIVA NUMBER(15),
 	CONSTRAINT PK_RECURSO_PLANETA PRIMARY KEY (PLANETA, TIPO_REC, NOME_REC),
	CONSTRAINT FK_RECURSO_PLANETA1 FOREIGN KEY (PLANETA)  REFERENCES PLANETA(ID) ON DELETE CASCADE,
	CONSTRAINT FK_RECURSO_PLANETA2 FOREIGN KEY (NOME_REC, TIPO_REC) REFERENCES RECURSO_NATURAL(NOME, TIPO) ON DELETE CASCADE
);

CREATE TABLE NAVE_COLONIZADORA (
	NAVE NUMBER(15),
 	CONSTRAINT PK_NAVE_COLONIZADORA PRIMARY KEY (NAVE),
	CONSTRAINT FK_NAVE_COLONIZADORA FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE
);

CREATE TABLE NAVE_CARGA(
 	NAVE NUMBER(15),
	CAPACIDADE_CARGA NUMBER(15) NOT NULL,
 	CONSTRAINT PK_NAVE_CARGA PRIMARY KEY (NAVE),
	CONSTRAINT FK_NAVE_CARGA FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE
);

CREATE TABLE NAVE_CIENTIFICA(
 	NAVE  NUMBER(15),
    CAPACIDADE_CARGA NUMBER(15) NOT NULL,
 	CONSTRAINT PK_NAVE_CIENTIFICA PRIMARY KEY (NAVE),
	CONSTRAINT FK_NAVE_CIENTIFICA FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE
);

CREATE TABLE PRODUTO_CIVILIZACAO (
	NOME_CIV VARCHAR2(50),
	CATEG_CIV CHAR(1),
	NOME_PRODUTO VARCHAR2(50),
	ORIGEM_PRODUTO VARCHAR2(50),
 	CONSTRAINT PK_ PRIMARY KEY (NOME_CIV, CATEG_CIV, NOME_PRODUTO, ORIGEM_PRODUTO),
	CONSTRAINT FK_PRODUTO_CIVILIZACAO1 FOREIGN KEY (NOME_PRODUTO, ORIGEM_PRODUTO) REFERENCES PRODUTO(NOME, ORIGEM) ON DELETE CASCADE,
	CONSTRAINT FK_PRODUTO_CIVILIZACAO2 FOREIGN KEY (NOME_CIV, CATEG_CIV) REFERENCES CIVILIZACAO(NOME, CATEGORIA) ON DELETE CASCADE
);

CREATE TABLE MISSAO_EXPLORACAO (
	MISSAO NUMBER(15),    
	NIVEL_IMPACTO_AMBIENTAL NUMBER(15),
	NAVE NUMBER(15) NOT NULL,
	PLANETA_BASE_DEST NUMBER(15) NOT NULL,
	NOME_BASE_DEST VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_MISSAO_EXPLORACAO PRIMARY KEY (MISSAO),
	CONSTRAINT FK_MISSAO_EXPLORACAO1 FOREIGN KEY (MISSAO) REFERENCES MISSAO_ESPACIAL(ID) ON DELETE CASCADE,
	CONSTRAINT FK_MISSAO_EXPLORACAO2 FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MISSAO_EXPLORACAO3 FOREIGN KEY (PLANETA_BASE_DEST, NOME_BASE_DEST) REFERENCES BASE_ESPACIAL(PLANETA, NOME) ON DELETE CASCADE
);

CREATE TABLE MISSAO_COMERCIO (
	MISSAO NUMBER(15),
	VERBA_MAXIMA NUMBER(15),
	NAVE NUMBER(15) NOT NULL,
	PLANETA_BASE_DEST NUMBER(15) NOT NULL,
	NOME_BASE_DEST VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_MISSAO_COMERCIO PRIMARY KEY (MISSAO),
	CONSTRAINT FK_MISSAO_COMERCIO1 FOREIGN KEY (MISSAO) REFERENCES MISSAO_ESPACIAL(ID) ON DELETE CASCADE,
	CONSTRAINT FK_MISSAO_COMERCIO2 FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE,
	CONSTRAINT FK_MISSAO_COMERCIO3 FOREIGN KEY (PLANETA_BASE_DEST, NOME_BASE_DEST) REFERENCES BASE_ESPACIAL(PLANETA, NOME) ON DELETE CASCADE
);

CREATE TABLE MISSAO_COLONIZACAO (
	MISSAO NUMBER(15),
	NAVE  NUMBER(15) NOT NULL,
	PLANETA NUMBER(15) NOT NULL,
	CONSTRAINT PK_MISSAO_COLONIZACAO PRIMARY KEY (MISSAO),
	CONSTRAINT FK_MISSAO_COLONIZACAO1 FOREIGN KEY (MISSAO) REFERENCES MISSAO_ESPACIAL(ID) ON DELETE CASCADE,
	CONSTRAINT FK_MISSAO_COLONIZACAO2 FOREIGN KEY (NAVE) REFERENCES NAVE(ID) ON DELETE CASCADE,
	CONSTRAINT FK_MISSAO_COLONIZACAO3 FOREIGN KEY (PLANETA) REFERENCES PLANETA(ID) ON DELETE CASCADE 
);

CREATE TABLE COMERCIO_PRODUTO (
	MISSAO NUMBER(15),
    NOME_PRODUTO VARCHAR(50),
	ORIGEM_PRODUTO VARCHAR2(50),
	NOME_CIV VARCHAR2(50),
	CATEG_CIV CHAR(1),
	TIPO_COMERCIO VARCHAR2(50) NOT NULL,
	QUANTIDADE NUMBER(15) NOT NULL,
	CONSTRAINT PK_COMERCIO_PRODUTO PRIMARY KEY (MISSAO, NOME_PRODUTO, ORIGEM_PRODUTO, NOME_CIV, CATEG_CIV),
	CONSTRAINT FK_COMERCIO_PRODUTO1 FOREIGN KEY (MISSAO) REFERENCES MISSAO_COMERCIO(MISSAO) ON DELETE CASCADE,
	CONSTRAINT FK_COMERCIO_PRODUTO2 FOREIGN KEY (NOME_CIV, CATEG_CIV, NOME_PRODUTO, ORIGEM_PRODUTO) REFERENCES PRODUTO_CIVILIZACAO(NOME_CIV, CATEG_CIV, NOME_PRODUTO, ORIGEM_PRODUTO) ON DELETE CASCADE
);

CREATE TABLE EQUIPAMENTOS(
	MISSAO_EXPLORACAO NUMBER(15),
	EQUIPAMENTO VARCHAR2(50),
	CONSTRAINT PK_EQUIPAMENTOS PRIMARY KEY (MISSAO_EXPLORACAO, EQUIPAMENTO),
	CONSTRAINT FK_EQUIPAMENTOS FOREIGN KEY (MISSAO_EXPLORACAO) REFERENCES MISSAO_EXPLORACAO(MISSAO) ON DELETE CASCADE
);
